version: "2"
services:
  execute:
    image: eduardoshanahan/fabric_boto:latest
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: echo REMOTE_USERNAME is $REMOTE_USERNAME in your Docker image
