version: "2"
services:
  execute:
    image: eduardoshanahan/fabric_boto:latest
    volumes:
      - ./scripts:/scripts
      - $LOCAL_PUBLIC_KEY_PATH:/$DOCKER_SSH_KEYS_PATH
    working_dir: /scripts
    environment:
      - REMOTE_USERNAME=$REMOTE_USERNAME
      - LOCAL_PUBLIC_KEY_PATH=$LOCAL_PUBLIC_KEY_PATH
      - PUBLIC_KEY_FILENAME=$PUBLIC_KEY_FILENAME
      - PRIVATE_KEY_FILENAME=$PRIVATE_KEY_FILENAME
      - DOCKER_SSH_KEYS_PATH=$DOCKER_SSH_KEYS_PATH
      - REMOTE_HOST=$REMOTE_HOST
      - REMOTE_ROOT_USERNAME=$REMOTE_ROOT_USERNAME
      - REMOTE_ROOT_PASSWORD=$REMOTE_ROOT_PASSWORD
    entrypoint: echo REMOTE_USERNAME is $REMOTE_USERNAME in your Docker image
